spring:
  application:
    name: RabbitMqApplication
  rabbitmq:
    password: guest
    username: guest
    host: 106.14.174.139
    port: 5672
    listener:
      simple:
        prefetch: 1  # ???????????????????????????